In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
import pickle

In [2]:
## Load Dataset
data = pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
## Preprocessing
data =data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [4]:
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
## Encode 1 Categorical Variable
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [6]:
data['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [7]:
## One Hot Encoding Geography
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo = OneHotEncoder(sparse_output=False)
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [8]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [9]:
geo_encoded_df = pd.DataFrame(
    geo_encoder,
    columns=onehot_encoder_geo.get_feature_names_out(['Geography'])
)

In [10]:
## Combine One hot encoded columns with original data
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)

In [11]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [12]:
## Sve the encoders and scalars for future use
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo,file)

In [13]:
## Divide the data into dependent and independent variables
X = data.drop('Exited', axis=1)
y = data['Exited']

## Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Scale the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [14]:
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler,file)

ANN Model Implementation

In [15]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

WARNING:tensorflow:From e:\DS\My Pro\Churn_Modelling_ANN\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [17]:
X_train = pd.DataFrame(X_train, columns=X.columns)
X_train.columns

Index(['CreditScore', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts',
       'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Geography_France',
       'Geography_Germany', 'Geography_Spain'],
      dtype='object')

In [18]:
## Build the ANN model
model = Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)), ## HL1 connected with I/P Layer
    Dense(32,activation='relu'), ## HL2
    Dense(1,activation='sigmoid') ## Output Layer
])

WARNING:tensorflow:From e:\DS\My Pro\Churn_Modelling_ANN\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [19]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [20]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.001)
loss=tf.keras.losses.BinaryCrossentropy()

In [21]:
## Compile the model
model.compile(optimizer=opt, loss=loss, metrics=['accuracy'])

In [22]:
## Set up the tesnorboard
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [23]:
## Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10,restore_best_weights=True)

In [24]:
### Train the model
history = model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=50, batch_size=32,
                    callbacks=[early_stopping_callback, tensorboard_callback])

Epoch 1/50
WARNING:tensorflow:From e:\DS\My Pro\Churn_Modelling_ANN\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From e:\DS\My Pro\Churn_Modelling_ANN\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 9s 12ms/step - loss: 0.4489 - accuracy: 0.8043 - val_loss: 0.3927 - val_accuracy: 0.8300
Epoch 2/50
250/250 [==============================] - 1s 5ms/step - loss: 0.3861 - accuracy: 0.8379 - val_loss: 0.3589 - val_accuracy: 0.8500
Epoch 3/50
250/250 [==============================] - 1s 4ms/step - loss: 0.3579 - accuracy: 0.8533 - val_loss: 0.3496 - val_accuracy: 0.8565
Epoch 4/50
250/250 [==============================] - 1s 4ms/step - loss: 0.3472 - accuracy: 0.8565 - val_loss: 0.3461 - val_accuracy: 0.8580
Epoch 5/50
250/250 [==============================] - 1s 4ms/step - loss: 0.3418 - accuracy: 0.8585 - val_loss: 0.3467 - val_accuracy: 0.8565
Epoch 6/50
250/250 [==============================] - 1s 5ms/step - loss: 0.3381 - accuracy: 0.8595 - val_loss: 0.3519 - val_accuracy: 0.8535
Epoch 7/50
250/250 [==============================] - 1s 5ms/step - loss: 0.3346 - accuracy: 0.8627 - val_loss: 0.3450 - val_accuracy: 0.8615
Epoch 8/50
250/250 [==============================] - 1s 6ms/step - loss: 0.3318 - accuracy: 0.8640 - val_loss: 0.3451 - val_accuracy: 0.8570
Epoch 9/50
250/250 [==============================] - 1s 5ms/step - loss: 0.3303 - accuracy: 0.8618 - val_loss: 0.3402 - val_accuracy: 0.8640
Epoch 10/50
250/250 [==============================] - 1s 4ms/step - loss: 0.3281 - accuracy: 0.8648 - val_loss: 0.3404 - val_accuracy: 0.8610
Epoch 11/50
250/250 [==============================] - 1s 4ms/step - loss: 0.3244 - accuracy: 0.8640 - val_loss: 0.3427 - val_accuracy: 0.8630
Epoch 12/50
250/250 [==============================] - 1s 4ms/step - loss: 0.3243 - accuracy: 0.8641 - val_loss: 0.3420 - val_accuracy: 0.8640
Epoch 13/50
250/250 [==============================] - 1s 4ms/step - loss: 0.3230 - accuracy: 0.8652 - val_loss: 0.3430 - val_accuracy: 0.8650
Epoch 14/50
250/250 [==============================] - 1s 4ms/step - loss: 0.3197 - accuracy: 0.8674 - val_loss: 0.3406 - val_accuracy: 0.8655
Epoch 15/50
250/250 [==============================] - 1s 4ms/step - loss: 0.3174 - accuracy: 0.8659 - val_loss: 0.3455 - val_accuracy: 0.8605
Epoch 16/50
250/250 [==============================] - 1s 4ms/step - loss: 0.3178 - accuracy: 0.8702 - val_loss: 0.3423 - val_accuracy: 0.8610
Epoch 17/50
250/250 [==============================] - 1s 4ms/step - loss: 0.3175 - accuracy: 0.8684 - val_loss: 0.3411 - val_accuracy: 0.8615
Epoch 18/50
250/250 [==============================] - 1s 4ms/step - loss: 0.3153 - accuracy: 0.8679 - val_loss: 0.3481 - val_accuracy: 0.8560
Epoch 19/50
250/250 [==============================] - 1s 4ms/step - loss: 0.3132 - accuracy: 0.8676 - val_loss: 0.3449 - val_accuracy: 0.8570

In [25]:
model.save('model.h5')

e:\DS\My Pro\Churn_Modelling_ANN\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [26]:
## Load tensorboard extension
%load_ext tensorboard

In [29]:
%tensorboard --logdir logs/fit

Launching TensorBoard...